apiVersion: v1
kind: Pod
metadata:
  name: kubectl
  labels:
    app: kubectl
spec:
  serviceAccountName: kubectl
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - sleep
        - "99999999999999"
