apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-ro
  namespace: default # Especificando o namespace onde a Role será aplicada
rules:
  - apiGroups: 
    - ""
    resources: 
    - "pods"
    verbs: 
    - "list"
  - apiGroups: 
    - batch
    resources: 
    - jobs
    verbs: 
    - list
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-ro
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ro
subjects:
  - kind: ServiceAccount # atrelar o RoleBinding a uma ServiceAccount
    name: kubectl # nome da ServiceAccount que será usada
    namespace: default # namespace da ServiceAccount

