apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: alpine
    image: alpine
    resources: {}
    command: 
      - "sleep"
      - "9999999999999"
    lifecycle:
      preStop:
        exec:
          command: 
            - sh
            - -c
            - curl 10.42.0.82
