apiVersion: batch/v1
kind: Job
metadata:
  name: echo-command
spec:
# Quando o job é finalizado e o pod estiver com status completado, ele será deletado após 0 segundos
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: 
        - "echo"
        - "Hello, Kubernetes!"
      restartPolicy: "OnFailure"
