apiVersion: batch/v1
kind: Job
metadata:
  name: echo-command
spec:
  #ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: 
        - "echo"
        - "Hello, Kubernetes!"
      restartPolicy: "OnFailure"
