apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    name: multi-pod
spec:
  containers:
  - name: httpd
    image: httpd
    resources: {}
  - name: debug
    image: alpine
    command:
      - "sleep"
      - "9999999999999"
    resources: {}
