apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      #creationTimestamp: null
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: nginx

          